export const MOCK_PRODUCTS = [
  {
    id: "prod_1",
    name: "Fresh Tomatoes",
    description: "Organic red tomatoes, fresh from local farms",
    price: 80,
    category: "Vegetables",
    stock: 50,
    unit: "kg",
    imageUrl: "https://images.unsplash.com/photo-1546470427-227e0b3c1eb7?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_2",
    name: "Fresh Potatoes",
    description: "High-quality potatoes perfect for all your cooking needs",
    price: 60,
    category: "Vegetables",
    stock: 100,
    unit: "kg",
    imageUrl:
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_3",
    name: "Fresh Onions",
    description: "Premium quality onions with great flavor",
    price: 70,
    category: "Vegetables",
    stock: 80,
    unit: "kg",
    imageUrl:
      "https://images.unsplash.com/photo-1508747703725-719777637510?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_4",
    name: "Red Apples",
    description: "Sweet and crispy red apples",
    price: 200,
    category: "Fruits",
    stock: 40,
    unit: "kg",
    imageUrl: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_5",
    name: "Fresh Bananas",
    description: "Ripe yellow bananas rich in potassium",
    price: 120,
    category: "Fruits",
    stock: 60,
    unit: "dozen",
    imageUrl:
      "https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_6",
    name: "Fresh Oranges",
    description: "Juicy oranges packed with vitamin C",
    price: 150,
    category: "Fruits",
    stock: 45,
    unit: "kg",
    imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_7",
    name: "Fresh Milk",
    description: "Pure cow milk, farm fresh",
    price: 140,
    category: "Dairy",
    stock: 30,
    unit: "L",
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_8",
    name: "Cheddar Cheese",
    description: "Premium quality cheddar cheese",
    price: 800,
    category: "Dairy",
    stock: 20,
    unit: "kg",
    imageUrl:
      "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_9",
    name: "Fresh Yogurt",
    description: "Creamy and delicious yogurt",
    price: 180,
    category: "Dairy",
    stock: 35,
    unit: "kg",
    imageUrl:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_10",
    name: "Chicken Breast",
    description: "Fresh boneless chicken breast",
    price: 550,
    category: "Meat",
    stock: 25,
    unit: "kg",
    imageUrl:
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_11",
    name: "Fresh Bread",
    description: "Soft and fluffy white bread",
    price: 80,
    category: "Bakery",
    stock: 50,
    unit: "pcs",
    imageUrl:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "prod_12",
    name: "Orange Juice",
    description: "100% pure orange juice",
    price: 250,
    category: "Beverages",
    stock: 40,
    unit: "L",
    imageUrl:
      "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const CATEGORIES = [
  "All",
  "Vegetables",
  "Fruits",
  "Dairy",
  "Meat",
  "Bakery",
  "Beverages",
  "Snacks",
  "Other",
];

export const UNITS = ["kg", "g", "L", "ml", "pcs", "dozen"];
